use_default_settings: true

general:
  instance_name: "interkid"

search:
  safe_search: 2
  autocomplete: "duckduckgo"
  formats:
    - html

server:
  secret_key: "ultrasecretkey"
  limiter: false
  image_proxy: true

ui:
  default_theme: simple
  theme_args:
    simple_style: light
  center_alignment: false
  query_in_title: false
  results_on_new_tab: false

preferences:
  lock:
    - safesearch
    - theme
    - simple_style
